version: "3.8"

services:
  api:
    build: dist/FunctionalLiving.Api/linux/
    container_name: functional-living-api
    hostname: functional-living-api
    restart: unless-stopped
    environment:
      Features__EnableSignalR: 'true'
      Features__EnableTracing: 'false'
      Features__SendToInflux: 'true'
      Features__SendToKnxSender: 'true'
      Features__SendToLog: 'true'
      Features__SendToSignalR: 'true'
      BaseUrl: http://localhost:9000
      Cors__0: http://localhost:9000
      Cors__1: http://blue:9000
      KnxSender__Endpoint: http://functional-living-knx-sender:9001
      InfluxDb__Endpoint: http://functional-living-influx:9999
      InfluxDb__Token: JBU-kgjsFW2q9lKmklFgHaVSHs8kp1nff6iMUxg_Xuj-KeuuY2Dc2LFDfJ5HDDvbvWqQeSEeb5c62Flr9X6QVA==
      InfluxDb__Bucket: functional-living
      InfluxDb__Organisation: cumps
      InfluxDb__LogLevel: None
      Tracing__Host: functional-living-jaeger
      Tracing__Port: 6831
      Tracing__ServiceName: FunctionalLiving.Api
      Serilog__WriteTo__1__Name: Seq
      Serilog__WriteTo__1__Args__ServerUrl: http://functional-living-seq:5341
    ports:
      - "9000:9000"
    depends_on:
      - seq
      - jaeger
      - influx
      - knx-sender
    links:
      - seq
      - jaeger
      - influx
      - knx-sender
    extra_hosts:
      - "functional-living-knx-sender:10.0.1.9"

  knx-listener:
    build: dist/FunctionalLiving.Knx.Listener/linux/
    container_name: functional-living-knx-listener
    hostname: functional-living-knx-listener
    restart: unless-stopped
    network_mode: host
    environment:
      Features__EnableTracing: 'false'
      Features__ConnectToKnx: 'true'
      Features__DebugKnxCemi: 'false'
      Features__SendToApi: 'true'
      Features__SendToLog: 'true'
      Features__UseKnxConnectionRouting: 'false'
      Features__UseKnxConnectionTunneling: 'true'
      Knx__RouterIp: 10.0.4.7
      Knx__RouterPort: 3671
      Knx__LocalPort: 3672
      Api__Endpoint: http://functional-living-api:9000
      Tracing__Host: functional-living-jaeger
      Tracing__Port: 9021
      Tracing__ServiceName: FunctionalLiving.Knx.Listener
      Serilog__MinimumLevel__Override__FunctionalLiving.Knx.Listener.Infrastructure.Modules.TogglesModule: Debug
      Serilog__MinimumLevel__Override__FunctionalLiving.Knx.Listener.KnxListener: Debug
      Serilog__WriteTo__1__Name: Seq
      Serilog__WriteTo__1__Args__ServerUrl: http://functional-living-seq:9016
    depends_on:
      - seq
      - jaeger
      - api
    extra_hosts:
      - "functional-living-seq:127.0.0.1"
      - "functional-living-jaeger:127.0.0.1"
      - "functional-living-api:127.0.0.1"

  knx-sender:
    build: dist/FunctionalLiving.Knx.Sender/linux/
    container_name: functional-living-knx-sender
    hostname: functional-living-knx-sender
    restart: unless-stopped
    network_mode: host
    environment:
      Features__EnableTracing: 'false'
      Features__ConnectToKnx: 'true'
      Features__DebugKnxCemi: 'false'
      Features__UseKnxConnectionRouting: 'false'
      Features__UseKnxConnectionTunneling: 'true'
      Knx__RouterIp: 10.0.4.7
      Knx__RouterPort: 3671
      Knx__LocalPort: 3671
      Tracing__Host: functional-living-jaeger
      Tracing__Port: 9021
      Tracing__ServiceName: FunctionalLiving.Knx.Sender
      Serilog__MinimumLevel__Override__FunctionalLiving.Knx.Listener.Infrastructure.Modules.TogglesModule: Debug
      Serilog__MinimumLevel__Override__FunctionalLiving.Knx.Listener.KnxSender: Debug
      Serilog__WriteTo__1__Name: Seq
      Serilog__WriteTo__1__Args__ServerUrl: http://functional-living-seq:9016
    depends_on:
      - seq
      - jaeger
    extra_hosts:
      - "functional-living-seq:127.0.0.1"
      - "functional-living-jaeger:127.0.0.1"

  homebridge:
    image: oznu/homebridge:latest
    container_name: functional-living-homebridge
    hostname: functional-living-homebridge
    restart: unless-stopped
    network_mode: host
    environment:
      - TZ=Europe/Brussels
      - HOMEBRIDGE_CONFIG_UI=1
      - HOMEBRIDGE_CONFIG_UI_PORT=9010
      - HOMEBRIDGE_INSECURE=1
    volumes:
      - homebridge:/homebridge
    depends_on:
      - api

  seq:
    image: datalust/seq
    container_name: functional-living-seq
    hostname: functional-living-seq
    restart: unless-stopped
    environment:
      ACCEPT_EULA: Y
    ports:
      - "9015:80"
      - "9016:5341"

  jaeger:
    image: jaegertracing/all-in-one:1.18
    container_name: functional-living-jaeger
    hostname: functional-living-jaeger
    restart: unless-stopped
    environment:
      SPAN_STORAGE_TYPE: badger
      BADGER_EPHEMERAL: 'false'
      BADGER_DIRECTORY_VALUE: /badger/data
      BADGER_DIRECTORY_KEY: /badger/key
    ports:
      - "9020:16686"
      - "9021:6831/udp"
    volumes:
      - jaeger:/badger

  influx:
    image: quay.io/influxdb/influxdb:2.0.0-beta
    container_name: functional-living-influx
    hostname: functional-living-influx
    restart: unless-stopped
    ports:
      - "9025:9999"
    volumes:
      - influxdb:/var/lib/influxdb2
    command: influxd run --reporting-disabled --bolt-path /var/lib/influxdb2/influxd.bolt --engine-path /var/lib/influxdb2/engine --store bolt

volumes:
  homebridge:
    name: functional-living-homebridge
  influxdb:
    name: functional-living-influx
  jaeger:
    name: functional-living-jaeger

# docker exec -it functional-living-influx /bin/bash
# influx setup
# * Enter a primary username.
# * Enter a password for your user.
# * Confirm your password by entering it again.
# * Enter a name for your primary organization.
# * Enter a name for your primary bucket.
# * Enter a retention period (in hours) for your primary bucket. Enter nothing for an infinite retention period.
# * Confirm the details for your primary user, organization, and bucket.
# * Go to http://localhost:9999/ to get your token

# docker exec -it functional-living-homebridge /bin/sh
# npm install --save
# docker logs -f functional-living-homebridge
# docker restart functional-living-homebridge
# or http://localhost:9010 with admin/admin
