version: "3.8"

services:
  api:
    build: dist/FunctionalLiving.Api/linux/
    container_name: functional-living-api
    hostname: functional-living-api
    environment:
      Serilog__WriteTo__1__Name: Seq
      Serilog__WriteTo__1__Args__ServerUrl: http://functional-living-seq:5341
    ports:
      - "9000:5000"
    depends_on:
      - seq
    links:
      - seq

  knx:
    build: dist/FunctionalLiving.Knx.Sender/linux/
    container_name: functional-living-knx
    hostname: functional-living-knx
    network_mode: host
    environment:
      Features__SendToLog: 'true'
      Features__SendToApi: 'true'
      Features__UseKnxConnectionTunneling: 'true'
      Knx__RouterIp: 10.0.4.7
      Api__Endpoint: http://functional-living-api:9000
      Serilog__MinimumLevel__Override__FunctionalLiving.Knx.Sender.Infrastructure.Modules.TogglesModule: Debug
      Serilog__MinimumLevel__Override__FunctionalLiving.Knx.Sender.KnxSender: Debug
      Serilog__WriteTo__1__Name: Seq
      Serilog__WriteTo__1__Args__ServerUrl: http://functional-living-seq:9002
    depends_on:
      - seq
      - api
    extra_hosts:
      - "functional-living-api:127.0.0.1"
      - "functional-living-seq:127.0.0.1"

  seq:
    image: datalust/seq
    container_name: functional-living-seq
    hostname: functional-living-seq
    environment:
      ACCEPT_EULA: Y
    ports:
      - "9001:80"
      - "9002:5341"
