version: "3.8"

services:
  api:
    build: dist/FunctionalLiving.Api/linux/
    container_name: functional-living-api
    hostname: functional-living-api
    environment:
      Features__SendToInflux: 'true'
      KnxSender__Endpoint: http://functional-living-knx-sender:9001
      InfluxDb__Endpoint: http://functional-living-influx:9999
      InfluxDb__Token: JBU-kgjsFW2q9lKmklFgHaVSHs8kp1nff6iMUxg_Xuj-KeuuY2Dc2LFDfJ5HDDvbvWqQeSEeb5c62Flr9X6QVA==
      InfluxDb__Bucket: functional-living
      InfluxDb__Organisation: cumps
      InfluxDb__LogLevel: None
      Serilog__WriteTo__1__Name: Seq
      Serilog__WriteTo__1__Args__ServerUrl: http://functional-living-seq:5341
    ports:
      - "9000:9000"
    depends_on:
      - seq
      - influx
      - knx-sender
    links:
      - seq
      - influx
      - knx-sender

  knx-listener:
    build: dist/FunctionalLiving.Knx.Listener/linux/
    container_name: functional-living-knx-listener
    hostname: functional-living-knx-listener
    network_mode: host
    environment:
      Features__SendToLog: 'true'
      Features__SendToApi: 'true'
      Features__UseKnxConnectionTunneling: 'true'
      Features__UseKnxConnectionRouting: 'false'
      Features__DebugKnxCemi: 'false'
      Knx__RouterIp: 10.0.4.7
      Knx__RouterPort: 3671
      Knx__LocalPort: 3672
      Api__Endpoint: http://functional-living-api:9000
      Serilog__MinimumLevel__Override__FunctionalLiving.Knx.Listener.Infrastructure.Modules.TogglesModule: Debug
      Serilog__MinimumLevel__Override__FunctionalLiving.Knx.Listener.KnxListener: Debug
      Serilog__WriteTo__1__Name: Seq
      Serilog__WriteTo__1__Args__ServerUrl: http://functional-living-seq:9011
    depends_on:
      - seq
      - api
    extra_hosts:
      - "functional-living-api:127.0.0.1"
      - "functional-living-seq:127.0.0.1"

  knx-sender:
    build: dist/FunctionalLiving.Knx.Sender/linux/
    container_name: functional-living-knx-sender
    hostname: functional-living-knx-sender
    network_mode: host
    environment:
      Features__UseKnxConnectionTunneling: 'true'
      Features__UseKnxConnectionRouting: 'false'
      Features__DebugKnxCemi: 'false'
      Knx__RouterIp: 10.0.4.7
      Knx__RouterPort: 3671
      Knx__LocalPort: 3671
      Serilog__MinimumLevel__Override__FunctionalLiving.Knx.Listener.Infrastructure.Modules.TogglesModule: Debug
      Serilog__MinimumLevel__Override__FunctionalLiving.Knx.Listener.KnxSender: Debug
      Serilog__WriteTo__1__Name: Seq
      Serilog__WriteTo__1__Args__ServerUrl: http://functional-living-seq:9011
    depends_on:
      - seq
    extra_hosts:
      - "functional-living-seq:127.0.0.1"

  seq:
    image: datalust/seq
    container_name: functional-living-seq
    hostname: functional-living-seq
    environment:
      ACCEPT_EULA: Y
    ports:
      - "9010:80"
      - "9011:5341"

  influx:
    image: quay.io/influxdb/influxdb:2.0.0-beta
    container_name: functional-living-influx
    hostname: functional-living-influx
    ports:
      - "9015:9999"
    volumes:
      - influxdb:/var/lib/influxdb2
    command: influxd run --reporting-disabled --bolt-path /var/lib/influxdb2/influxd.bolt --engine-path /var/lib/influxdb2/engine --store bolt

volumes:
  influxdb:
    name: functional-living-influx

# docker exec -it influxdb /bin/bash
# influx setup
# * Enter a primary username.
# * Enter a password for your user.
# * Confirm your password by entering it again.
# * Enter a name for your primary organization.
# * Enter a name for your primary bucket.
# * Enter a retention period (in hours) for your primary bucket. Enter nothing for an infinite retention period.
# * Confirm the details for your primary user, organization, and bucket.
# * Go to http://localhost:9999/ to get your token
