version: "3.7"

services:
  api:
    build: dist/FunctionalLiving.Api/linux/
    container_name: functional-living-api
    hostname: functional-living-api
    environment:
      Serilog__WriteTo__1__Name: Seq
      Serilog__WriteTo__1__Args__ServerUrl: http://functional-living-seq:5341
    ports:
      - "9000:5000"
    depends_on:
      - seq
    links:
      - seq

  knx:
    build: dist/FunctionalLiving.Knx.Sender/linux/
    container_name: functional-living-knx
    hostname: functional-living-knx
    environment:
      Knx__RouterIp: 10.0.4.7
      Api__Endpoint: http://functional-living-api:5000
      Serilog__WriteTo__1__Name: Seq
      Serilog__WriteTo__1__Args__ServerUrl: http://functional-living-seq:5341
    depends_on:
      - seq
      - api
    links:
      - seq
      - api

  seq:
    image: datalust/seq
    container_name: functional-living-seq
    hostname: functional-living-seq
    environment:
      ACCEPT_EULA: Y
    ports:
      - "9001:80"
