// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyVersionAttribute("2.0.0.0")>]
[<assembly: AssemblyFileVersionAttribute("2.0.0.0")>]
[<assembly: AssemblyInformationalVersionAttribute("")>]
[<assembly: AssemblyProductAttribute("Functional Living")>]
[<assembly: AssemblyCopyrightAttribute("Copyright (c) Cumps Consulting")>]
[<assembly: AssemblyCompanyAttribute("Cumps Consulting")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyVersion = "2.0.0.0"
    let [<Literal>] AssemblyFileVersion = "2.0.0.0"
    let [<Literal>] AssemblyInformationalVersion = ""
    let [<Literal>] AssemblyProduct = "Functional Living"
    let [<Literal>] AssemblyCopyright = "Copyright (c) Cumps Consulting"
    let [<Literal>] AssemblyCompany = "Cumps Consulting"
