namespace FunctionalLiving.Domain.Knx
{
    using System.Collections.Generic;
    using FunctionalLiving.Knx.Addressing;

    internal static class CustomerData
    {
        public static readonly List<KnxObject> KnxObjects = new List<KnxObject>
        {
            new KnxObject(KnxControlType.Feedback, KnxDataType.Switch, KnxGroupAddress.Parse("0/1/0"), "Verlichting - Leefruimte - Spots TV - Aan/Uit"),
            new KnxObject(KnxControlType.Feedback, KnxDataType.Switch, KnxGroupAddress.Parse("0/1/1"), "Verlichting - Leefruimte - Spots Zetel - Aan/Uit"),
            new KnxObject(KnxControlType.Feedback, KnxDataType.Switch, KnxGroupAddress.Parse("0/1/2"), "Verlichting - Leefruimte - Spots Piano - Aan/Uit"),
            new KnxObject(KnxControlType.Feedback, KnxDataType.Switch, KnxGroupAddress.Parse("0/1/3"), "Verlichting - Keuken - Spots - Aan/Uit"),
            new KnxObject(KnxControlType.Feedback, KnxDataType.Switch, KnxGroupAddress.Parse("0/1/4"), "Verlichting - Trap - Spots - Aan/Uit"),
            new KnxObject(KnxControlType.Feedback, KnxDataType.Switch, KnxGroupAddress.Parse("0/1/5"), "Verlichting - Nachthal - Spots - Aan/Uit"),
            new KnxObject(KnxControlType.Feedback, KnxDataType.Switch, KnxGroupAddress.Parse("0/1/6"), "Verlichting - Badkamer - Spots - Aan/Uit"),
            new KnxObject(KnxControlType.Feedback, KnxDataType.Switch, KnxGroupAddress.Parse("0/1/7"), "Verlichting - Bureau - Spots Binnencirkel - Aan/Uit"),
            new KnxObject(KnxControlType.Feedback, KnxDataType.Switch, KnxGroupAddress.Parse("0/1/8"), "Verlichting - Bureau - Spots Buitencirkel - Aan/Uit"),
            new KnxObject(KnxControlType.Feedback, KnxDataType.Switch, KnxGroupAddress.Parse("0/1/9"), "Verlichting - Toilet Boven - Spot - Aan/Uit"),
            new KnxObject(KnxControlType.Feedback, KnxDataType.Switch, KnxGroupAddress.Parse("0/1/10"), "Verlichting - Garage - Centraal - Aan/Uit"),
            new KnxObject(KnxControlType.Feedback, KnxDataType.Switch, KnxGroupAddress.Parse("0/1/11"), "Verlichting - Berging - Centraal - Aan/Uit"),
            new KnxObject(KnxControlType.Feedback, KnxDataType.Switch, KnxGroupAddress.Parse("0/1/12"), "Verlichting - Inkomhal - Centraal - Aan/Uit"),
            new KnxObject(KnxControlType.Feedback, KnxDataType.Switch, KnxGroupAddress.Parse("0/1/13"), "Verlichting - Toilet Beneden - Wastafel - Aan/Uit"),
            new KnxObject(KnxControlType.Feedback, KnxDataType.Switch, KnxGroupAddress.Parse("0/1/14"), "Verlichting - Leefruimte - Eettafel - Aan/Uit"),
            new KnxObject(KnxControlType.Feedback, KnxDataType.Switch, KnxGroupAddress.Parse("0/1/15"), "Verlichting - Badkamer - Makeup - Aan/Uit"),
            new KnxObject(KnxControlType.Feedback, KnxDataType.Switch, KnxGroupAddress.Parse("0/1/16"), "Verlichting - Abby - Centraal - Aan/Uit"),
            new KnxObject(KnxControlType.Feedback, KnxDataType.Switch, KnxGroupAddress.Parse("0/1/17"), "Verlichting - Opslag - Centraal - Aan/Uit"),
            new KnxObject(KnxControlType.Feedback, KnxDataType.Switch, KnxGroupAddress.Parse("0/1/18"), "Verlichting - David - Centraal - Aan/Uit"),
            new KnxObject(KnxControlType.Feedback, KnxDataType.Switch, KnxGroupAddress.Parse("0/1/19"), "Verlichting - Badkamer - Spiegel - Aan/Uit"),
            new KnxObject(KnxControlType.Feedback, KnxDataType.Switch, KnxGroupAddress.Parse("0/1/20"), "Verlichting - Garage - Onder Trap - Aan/Uit"),
            new KnxObject(KnxControlType.Feedback, KnxDataType.Switch, KnxGroupAddress.Parse("0/1/21"), "Verlichting - Zoldertrap - Wand - Aan/Uit"),
            new KnxObject(KnxControlType.Feedback, KnxDataType.Switch, KnxGroupAddress.Parse("0/1/22"), "Verlichting - Bureau - Centraal - Aan/Uit"),
            new KnxObject(KnxControlType.Feedback, KnxDataType.Switch, KnxGroupAddress.Parse("0/1/23"), "Verlichting - Keuken - Eiland - Aan/Uit"),
            new KnxObject(KnxControlType.Feedback, KnxDataType.Switch, KnxGroupAddress.Parse("0/1/24"), "Verlichting - Leefruimte - Spots Dressoir - Aan/Uit"),

            new KnxObject(KnxControlType.Feedback, KnxDataType.Switch, KnxGroupAddress.Parse("1/1/0"), "Toestellen - Dampkap - Aan/Uit"),
            new KnxObject(KnxControlType.Feedback, KnxDataType.Switch, KnxGroupAddress.Parse("1/1/1"), "Toestellen - Kookplaat - Aan/Uit"),
            new KnxObject(KnxControlType.Feedback, KnxDataType.Switch, KnxGroupAddress.Parse("1/1/2"), "Toestellen - Oven - Aan/Uit"),
            new KnxObject(KnxControlType.Feedback, KnxDataType.Switch, KnxGroupAddress.Parse("1/1/3"), "Toestellen - Microgolf - Aan/Uit"),
            new KnxObject(KnxControlType.Feedback, KnxDataType.Switch, KnxGroupAddress.Parse("1/1/4"), "Toestellen - Vaatwas - Aan/Uit"),
            new KnxObject(KnxControlType.Feedback, KnxDataType.Switch, KnxGroupAddress.Parse("1/1/5"), "Toestellen - Droogkast - Aan/Uit"),
            new KnxObject(KnxControlType.Feedback, KnxDataType.Switch, KnxGroupAddress.Parse("1/1/6"), "Toestellen - Wasmachine - Aan/Uit"),
            new KnxObject(KnxControlType.Feedback, KnxDataType.Switch, KnxGroupAddress.Parse("1/1/7"), "Toestellen - Diepvries - Aan/Uit"),
            new KnxObject(KnxControlType.Feedback, KnxDataType.Switch, KnxGroupAddress.Parse("1/1/8"), "Toestellen - Koelkast - Aan/Uit"),
            new KnxObject(KnxControlType.Feedback, KnxDataType.Switch, KnxGroupAddress.Parse("1/1/9"), "Toestellen - Handdoekdroger - Aan/Uit"),
            new KnxObject(KnxControlType.Feedback, KnxDataType.Switch, KnxGroupAddress.Parse("1/1/10"), "Toestellen - Stopcontacten Buiten - Aan/Uit"),

            new KnxObject(KnxControlType.Feedback, KnxDataType.Switch, KnxGroupAddress.Parse("1/3/3"), "Boiler - Pomp - Aan/Uit"),
            new KnxObject(KnxControlType.Feedback, KnxDataType.Switch, KnxGroupAddress.Parse("1/3/7"), "Zonnecollector - Pomp - Aan/Uit"),
            new KnxObject(KnxControlType.Feedback, KnxDataType.Switch, KnxGroupAddress.Parse("1/3/13"), "Vloerverwarming - Pomp - Aan/Uit"),
            new KnxObject(KnxControlType.Feedback, KnxDataType.Switch, KnxGroupAddress.Parse("1/3/19"), "Warmwater - Pomp - Aan/Uit"),

            new KnxObject(KnxControlType.Control, KnxDataType.Switch, KnxGroupAddress.Parse("2/1/1"), "Verlichting - Voordeur - Aan/Uit"),
            new KnxObject(KnxControlType.Control, KnxDataType.Switch, KnxGroupAddress.Parse("2/1/10"), "Verlichting - Tuin - Zijmuur - Aan/Uit"),
            new KnxObject(KnxControlType.Control, KnxDataType.Switch, KnxGroupAddress.Parse("2/1/11"), "Verlichting - Tuin - Terras - Aan/Uit"),

            new KnxObject(KnxControlType.Control, KnxDataType.Switch, KnxGroupAddress.Parse("2/2/1"), "Verlichting - Inkomhal - Centraal - Aan/Uit", KnxGroupAddress.Parse("0/1/12")),
            new KnxObject(KnxControlType.Control, KnxDataType.Switch, KnxGroupAddress.Parse("2/2/2"), "Verlichting - Toilet Beneden - Wastafel - Aan/Uit", KnxGroupAddress.Parse("0/1/13")),
            new KnxObject(KnxControlType.Control, KnxDataType.Switch, KnxGroupAddress.Parse("2/2/10"), "Verlichting - Leefruimte - Eettafel - Aan/Uit", KnxGroupAddress.Parse("0/1/14")),
            new KnxObject(KnxControlType.Control, KnxDataType.Switch, KnxGroupAddress.Parse("2/2/11"), "Verlichting - Leefruimte - Spots Piano - Aan/Uit", KnxGroupAddress.Parse("0/1/2")),
            new KnxObject(KnxControlType.Control, KnxDataType.Switch, KnxGroupAddress.Parse("2/2/12"), "Verlichting - Leefruimte - Spots TV - Aan/Uit", KnxGroupAddress.Parse("0/1/0")),
            new KnxObject(KnxControlType.Control, KnxDataType.Switch, KnxGroupAddress.Parse("2/2/13"), "Verlichting - Leefruimte - Spots Zetel - Aan/Uit", KnxGroupAddress.Parse("0/1/1")),
            new KnxObject(KnxControlType.Control, KnxDataType.Switch, KnxGroupAddress.Parse("2/2/14"), "Verlichting - Leefruimte - Spots TV + Zetel - Aan/Uit"),
            new KnxObject(KnxControlType.Control, KnxDataType.Switch, KnxGroupAddress.Parse("2/2/15"), "Verlichting - Leefruimte - Spots Dressoir - Aan/Uit", KnxGroupAddress.Parse("0/1/24")),
            new KnxObject(KnxControlType.Control, KnxDataType.Switch, KnxGroupAddress.Parse("2/2/20"), "Verlichting - Keuken - Eiland - Aan/Uit", KnxGroupAddress.Parse("0/1/23")),
            new KnxObject(KnxControlType.Control, KnxDataType.Switch, KnxGroupAddress.Parse("2/2/21"), "Verlichting - Keuken - Spots - Aan/Uit", KnxGroupAddress.Parse("0/1/3")),
            new KnxObject(KnxControlType.Control, KnxDataType.Switch, KnxGroupAddress.Parse("2/2/30"), "Verlichting - Berging - Centraal - Aan/Uit", KnxGroupAddress.Parse("0/1/11")),
            new KnxObject(KnxControlType.Control, KnxDataType.Switch, KnxGroupAddress.Parse("2/2/40"), "Verlichting - Garage - Centraal - Aan/Uit", KnxGroupAddress.Parse("0/1/10")),
            new KnxObject(KnxControlType.Control, KnxDataType.Switch, KnxGroupAddress.Parse("2/2/41"), "Verlichting - Garage - Onder Trap - Aan/Uit", KnxGroupAddress.Parse("0/1/20")),

            new KnxObject(KnxControlType.Control, KnxDataType.Switch, KnxGroupAddress.Parse("2/3/1"), "Verlichting - Trap - Spots - Aan/Uit", KnxGroupAddress.Parse("0/1/4")),
            new KnxObject(KnxControlType.Control, KnxDataType.Switch, KnxGroupAddress.Parse("2/3/2"), "Verlichting - Trap - Muur - Aan/Uit"),
            new KnxObject(KnxControlType.Control, KnxDataType.Switch, KnxGroupAddress.Parse("2/3/3"), "Verlichting - Trap - Spots + Muur - Aan/Uit"),
            new KnxObject(KnxControlType.Control, KnxDataType.Switch, KnxGroupAddress.Parse("2/3/10"), "Verlichting - Nachthal - Spots - Aan/Uit", KnxGroupAddress.Parse("0/1/5")),
            new KnxObject(KnxControlType.Control, KnxDataType.Switch, KnxGroupAddress.Parse("2/3/11"), "Verlichting - Trap + Nachthal - Spots - Aan/Uit"),
            new KnxObject(KnxControlType.Control, KnxDataType.Switch, KnxGroupAddress.Parse("2/3/20"), "Verlichting - Badkamer - Spots - Aan/Uit", KnxGroupAddress.Parse("0/1/6")),
            new KnxObject(KnxControlType.Control, KnxDataType.Switch, KnxGroupAddress.Parse("2/3/21"), "Verlichting - Badkamer - Spiegel - Aan/Uit", KnxGroupAddress.Parse("0/1/19")),
            new KnxObject(KnxControlType.Control, KnxDataType.Switch, KnxGroupAddress.Parse("2/3/22"), "Verlichting - Badkamer - Makeup - Aan/Uit", KnxGroupAddress.Parse("0/1/15")),
            new KnxObject(KnxControlType.Control, KnxDataType.Switch, KnxGroupAddress.Parse("2/3/30"), "Verlichting - Bureau - Centraal - Aan/Uit", KnxGroupAddress.Parse("0/1/22")),
            new KnxObject(KnxControlType.Control, KnxDataType.Switch, KnxGroupAddress.Parse("2/3/31"), "Verlichting - Bureau - Spots Buitencirkel - Aan/Uit", KnxGroupAddress.Parse("0/1/7")),
            new KnxObject(KnxControlType.Control, KnxDataType.Switch, KnxGroupAddress.Parse("2/3/32"), "Verlichting - Bureau - Spots Binnencirkel - Aan/Uit", KnxGroupAddress.Parse("0/1/8")),
            new KnxObject(KnxControlType.Control, KnxDataType.Switch, KnxGroupAddress.Parse("2/3/33"), "Verlichting - Bureau - Spots - Aan/Uit"),
            new KnxObject(KnxControlType.Control, KnxDataType.Switch, KnxGroupAddress.Parse("2/3/40"), "Verlichting - David - Centraal - Aan/Uit", KnxGroupAddress.Parse("0/1/18")),
            new KnxObject(KnxControlType.Control, KnxDataType.Switch, KnxGroupAddress.Parse("2/3/41"), "Verlichting - David - Bed Links - Aan/Uit"),
            new KnxObject(KnxControlType.Control, KnxDataType.Switch, KnxGroupAddress.Parse("2/3/42"), "Verlichting - David - Bed Rechts - Aan/Uit"),
            new KnxObject(KnxControlType.Control, KnxDataType.Switch, KnxGroupAddress.Parse("2/3/50"), "Verlichting - Opslag - Centraal - Aan/Uit", KnxGroupAddress.Parse("0/1/17")),
            new KnxObject(KnxControlType.Control, KnxDataType.Switch, KnxGroupAddress.Parse("2/3/60"), "Verlichting - Abby - Centraal - Aan/Uit", KnxGroupAddress.Parse("0/1/16")),
            new KnxObject(KnxControlType.Control, KnxDataType.Switch, KnxGroupAddress.Parse("2/3/70"), "Verlichting - Toilet Boven - Spot - Aan/Uit", KnxGroupAddress.Parse("0/1/9")),

            new KnxObject(KnxControlType.Control, KnxDataType.Switch, KnxGroupAddress.Parse("2/4/1"), "Verlichting - Zoldertrap - Wand - Aan/Uit", KnxGroupAddress.Parse("0/1/21")),

            new KnxObject(KnxControlType.Control, KnxDataType.Switch, KnxGroupAddress.Parse("5/1/0"), "Toestellen - Stopcontacten Buiten - Aan/Uit"),
            new KnxObject(KnxControlType.Control, KnxDataType.Switch, KnxGroupAddress.Parse("5/2/0"), "Toestellen - Dampkap - Aan/Uit"),
            new KnxObject(KnxControlType.Control, KnxDataType.Switch, KnxGroupAddress.Parse("5/2/1"), "Toestellen - Kookplaat - Aan/Uit"),
            new KnxObject(KnxControlType.Control, KnxDataType.Switch, KnxGroupAddress.Parse("5/2/2"), "Toestellen - Oven - Aan/Uit"),
            new KnxObject(KnxControlType.Control, KnxDataType.Switch, KnxGroupAddress.Parse("5/2/3"), "Toestellen - Microgolf - Aan/Uit"),
            new KnxObject(KnxControlType.Control, KnxDataType.Switch, KnxGroupAddress.Parse("5/2/4"), "Toestellen - Vaatwas - Aan/Uit"),
            new KnxObject(KnxControlType.Control, KnxDataType.Switch, KnxGroupAddress.Parse("5/2/5"), "Toestellen - Droogkast - Aan/Uit"),
            new KnxObject(KnxControlType.Control, KnxDataType.Switch, KnxGroupAddress.Parse("5/2/6"), "Toestellen - Wasmachine - Aan/Uit"),
            new KnxObject(KnxControlType.Control, KnxDataType.Switch, KnxGroupAddress.Parse("5/2/7"), "Toestellen - Diepvries - Aan/Uit"),
            new KnxObject(KnxControlType.Control, KnxDataType.Switch, KnxGroupAddress.Parse("5/2/8"), "Toestellen - Koelkast - Aan/Uit"),
            new KnxObject(KnxControlType.Control, KnxDataType.Switch, KnxGroupAddress.Parse("5/3/0"), "Toestellen - Handdoekdroger - Aan/Uit"),

            new KnxObject(KnxControlType.Feedback, KnxDataType.Toggle, KnxGroupAddress.Parse("0/5/0"), "Beweging in inkomhal"),
            new KnxObject(KnxControlType.Feedback, KnxDataType.Toggle, KnxGroupAddress.Parse("0/5/1"), "Beweging in toilet beneden"),
            new KnxObject(KnxControlType.Feedback, KnxDataType.Toggle, KnxGroupAddress.Parse("0/5/2"), "Beweging in berging"),
            new KnxObject(KnxControlType.Feedback, KnxDataType.Toggle, KnxGroupAddress.Parse("0/5/3"), "Beweging in garage"),
            new KnxObject(KnxControlType.Feedback, KnxDataType.Toggle, KnxGroupAddress.Parse("0/5/4"), "Beweging in nachthal trap"),
            new KnxObject(KnxControlType.Feedback, KnxDataType.Toggle, KnxGroupAddress.Parse("0/5/5"), "Beweging in nachthal badkamer"),
            new KnxObject(KnxControlType.Feedback, KnxDataType.Toggle, KnxGroupAddress.Parse("0/5/6"), "Beweging in badkamer"),
            new KnxObject(KnxControlType.Feedback, KnxDataType.Toggle, KnxGroupAddress.Parse("0/5/7"), "Beweging in toilet boven"),

            new KnxObject(KnxControlType.Feedback, KnxDataType.Toggle, KnxGroupAddress.Parse("1/0/1"), "Neerslag buiten"),
            new KnxObject(KnxControlType.Feedback, KnxDataType.Toggle, KnxGroupAddress.Parse("1/0/2"), "Droog buiten"),

            new KnxObject(KnxControlType.Feedback, KnxDataType.Percentage, KnxGroupAddress.Parse("0/2/0"), "Verlichting - Leefruimte - Spots TV - Dimmen"),
            new KnxObject(KnxControlType.Feedback, KnxDataType.Percentage, KnxGroupAddress.Parse("0/2/1"), "Verlichting - Leefruimte - Spots Zetel - Dimmen"),
            new KnxObject(KnxControlType.Feedback, KnxDataType.Percentage, KnxGroupAddress.Parse("0/2/2"), "Verlichting - Leefruimte - Spots Piano - Dimmen"),
            new KnxObject(KnxControlType.Feedback, KnxDataType.Percentage, KnxGroupAddress.Parse("0/2/3"), "Verlichting - Keuken - Spots - Dimmen"),
            new KnxObject(KnxControlType.Feedback, KnxDataType.Percentage, KnxGroupAddress.Parse("0/2/4"), "Verlichting - Trap - Spots - Dimmen"),
            new KnxObject(KnxControlType.Feedback, KnxDataType.Percentage, KnxGroupAddress.Parse("0/2/5"), "Verlichting - Nachthal - Spots - Dimmen"),
            new KnxObject(KnxControlType.Feedback, KnxDataType.Percentage, KnxGroupAddress.Parse("0/2/6"), "Verlichting - Badkamer - Spots - Dimmen"),
            new KnxObject(KnxControlType.Feedback, KnxDataType.Percentage, KnxGroupAddress.Parse("0/2/7"), "Verlichting - Bureau - Spots Binnencirkel - Dimmen"),
            new KnxObject(KnxControlType.Feedback, KnxDataType.Percentage, KnxGroupAddress.Parse("0/2/8"), "Verlichting - Bureau - Spots Buitencirkel - Dimmen"),
            new KnxObject(KnxControlType.Feedback, KnxDataType.Percentage, KnxGroupAddress.Parse("0/2/9"), "Verlichting - Abby - Centraal - Dimmen"),
            new KnxObject(KnxControlType.Feedback, KnxDataType.Percentage, KnxGroupAddress.Parse("0/2/10"), "Verlichting - Opslag - Centraal - Dimmen"),
            new KnxObject(KnxControlType.Feedback, KnxDataType.Percentage, KnxGroupAddress.Parse("0/2/11"), "Verlichting - David - Centraal - Dimmen"),
            new KnxObject(KnxControlType.Feedback, KnxDataType.Percentage, KnxGroupAddress.Parse("0/2/12"), "Verlichting - Bureau - Centraal - Dimmen"),
            new KnxObject(KnxControlType.Feedback, KnxDataType.Percentage, KnxGroupAddress.Parse("0/2/13"), "Verlichting - Toilet Boven - Spot - Dimmen"),
            new KnxObject(KnxControlType.Feedback, KnxDataType.Percentage, KnxGroupAddress.Parse("0/2/14"), "Verlichting - Keuken - Eiland - Dimmen"),
            new KnxObject(KnxControlType.Feedback, KnxDataType.Percentage, KnxGroupAddress.Parse("0/2/15"), "Verlichting - Leefruimte - Spots Dressoir - Dimmen"),

            // TODO: Double check if it is relative or absolute dimming
            new KnxObject(KnxControlType.Control, KnxDataType.Percentage, KnxGroupAddress.Parse("3/2/11"), "Verlichting - Leefruimte - Spots Piano - Dimmen Relatief"),
            new KnxObject(KnxControlType.Control, KnxDataType.Percentage, KnxGroupAddress.Parse("3/2/12"), "Verlichting - Leefruimte - Spots TV - Dimmen Relatief"),
            new KnxObject(KnxControlType.Control, KnxDataType.Percentage, KnxGroupAddress.Parse("3/2/13"), "Verlichting - Leefruimte - Spots Zetel - Dimmen Relatief"),
            new KnxObject(KnxControlType.Control, KnxDataType.Percentage, KnxGroupAddress.Parse("3/2/14"), "Verlichting - Leefruimte - Spots TV + Zetel - Dimmen Relatief"),
            new KnxObject(KnxControlType.Control, KnxDataType.Percentage, KnxGroupAddress.Parse("3/2/15"), "Verlichting - Leefruimte - Spots Dressoir - Dimmen Relatief"),
            new KnxObject(KnxControlType.Control, KnxDataType.Percentage, KnxGroupAddress.Parse("3/2/20"), "Verlichting - Keuken - Eiland - Dimmen Relatief"),
            new KnxObject(KnxControlType.Control, KnxDataType.Percentage, KnxGroupAddress.Parse("3/2/21"), "Verlichting - Keuken - Spots - Dimmen Relatief"),

            new KnxObject(KnxControlType.Control, KnxDataType.Percentage, KnxGroupAddress.Parse("3/3/1"), "Verlichting - Trap - Spots - Dimmen Relatief"),
            new KnxObject(KnxControlType.Control, KnxDataType.Percentage, KnxGroupAddress.Parse("3/3/10"), "Verlichting - Nachthal - Spots - Dimmen Relatief"),
            new KnxObject(KnxControlType.Control, KnxDataType.Percentage, KnxGroupAddress.Parse("3/3/20"), "Verlichting - Badkamer - Spots - Dimmen Relatief"),
            new KnxObject(KnxControlType.Control, KnxDataType.Percentage, KnxGroupAddress.Parse("3/3/30"), "Verlichting - Bureau - Centraal - Dimmen Relatief"),
            new KnxObject(KnxControlType.Control, KnxDataType.Percentage, KnxGroupAddress.Parse("3/3/31"), "Verlichting - Bureau - Spots Buitencirkel - Dimmen Relatief"),
            new KnxObject(KnxControlType.Control, KnxDataType.Percentage, KnxGroupAddress.Parse("3/3/32"), "Verlichting - Bureau - Spots Binnencirkel - Dimmen Relatief"),
            new KnxObject(KnxControlType.Control, KnxDataType.Percentage, KnxGroupAddress.Parse("3/3/33"), "Verlichting - Bureau - Spots - Dimmen Relatief"),
            new KnxObject(KnxControlType.Control, KnxDataType.Percentage, KnxGroupAddress.Parse("3/3/40"), "Verlichting - David - Centraal - Dimmen Relatief"),
            new KnxObject(KnxControlType.Control, KnxDataType.Percentage, KnxGroupAddress.Parse("3/3/50"), "Verlichting - Opslag - Centraal - Dimmen Relatief"),
            new KnxObject(KnxControlType.Control, KnxDataType.Percentage, KnxGroupAddress.Parse("3/3/60"), "Verlichting - Abby - Centraal - Dimmen Relatief"),
            new KnxObject(KnxControlType.Control, KnxDataType.Percentage, KnxGroupAddress.Parse("3/3/70"), "Verlichting - Toilet Boven - Spot - Dimmen Relatief"),

            // TODO: Double check if it is relative or absolute dimming
            new KnxObject(KnxControlType.Control, KnxDataType.Percentage, KnxGroupAddress.Parse("4/2/11"), "Verlichting - Leefruimte - Spots Piano - Dimmen Absoluut"),
            new KnxObject(KnxControlType.Control, KnxDataType.Percentage, KnxGroupAddress.Parse("4/2/12"), "Verlichting - Leefruimte - Spots TV - Dimmen Absoluut"),
            new KnxObject(KnxControlType.Control, KnxDataType.Percentage, KnxGroupAddress.Parse("4/2/13"), "Verlichting - Leefruimte - Spots Zetel - Dimmen Absoluut"),
            new KnxObject(KnxControlType.Control, KnxDataType.Percentage, KnxGroupAddress.Parse("4/2/14"), "Verlichting - Leefruimte - Spots TV + Zetel - Dimmen Absoluut"),
            new KnxObject(KnxControlType.Control, KnxDataType.Percentage, KnxGroupAddress.Parse("4/2/15"), "Verlichting - Leefruimte - Spots Dressoir - Dimmen Absoluut"),
            new KnxObject(KnxControlType.Control, KnxDataType.Percentage, KnxGroupAddress.Parse("4/2/20"), "Verlichting - Keuken - Eiland - Dimmen Absoluut"),
            new KnxObject(KnxControlType.Control, KnxDataType.Percentage, KnxGroupAddress.Parse("4/2/21"), "Verlichting - Keuken - Spots - Dimmen Absoluut"),

            new KnxObject(KnxControlType.Control, KnxDataType.Percentage, KnxGroupAddress.Parse("4/3/1"), "Verlichting - Trap - Spots - Dimmen Absoluut"),
            new KnxObject(KnxControlType.Control, KnxDataType.Percentage, KnxGroupAddress.Parse("4/3/10"), "Verlichting - Nachthal - Spots - Dimmen Absoluut"),
            new KnxObject(KnxControlType.Control, KnxDataType.Percentage, KnxGroupAddress.Parse("4/3/20"), "Verlichting - Badkamer - Spots - Dimmen Absoluut"),
            new KnxObject(KnxControlType.Control, KnxDataType.Percentage, KnxGroupAddress.Parse("4/3/30"), "Verlichting - Bureau - Centraal - Dimmen Absoluut"),
            new KnxObject(KnxControlType.Control, KnxDataType.Percentage, KnxGroupAddress.Parse("4/3/31"), "Verlichting - Bureau - Spots Buitencirkel - Absoluut Relatief"),
            new KnxObject(KnxControlType.Control, KnxDataType.Percentage, KnxGroupAddress.Parse("4/3/32"), "Verlichting - Bureau - Spots Binnencirkel - Absoluut Relatief"),
            new KnxObject(KnxControlType.Control, KnxDataType.Percentage, KnxGroupAddress.Parse("4/3/33"), "Verlichting - Bureau - Spots - Dimmen Absoluut"),
            new KnxObject(KnxControlType.Control, KnxDataType.Percentage, KnxGroupAddress.Parse("4/3/40"), "Verlichting - David - Centraal - Dimmen Absoluut"),
            new KnxObject(KnxControlType.Control, KnxDataType.Percentage, KnxGroupAddress.Parse("4/3/50"), "Verlichting - Opslag - Centraal - Dimmen Absoluut"),
            new KnxObject(KnxControlType.Control, KnxDataType.Percentage, KnxGroupAddress.Parse("4/3/60"), "Verlichting - Abby - Centraal - Dimmen Absoluut"),
            new KnxObject(KnxControlType.Control, KnxDataType.Percentage, KnxGroupAddress.Parse("4/3/70"), "Verlichting - Toilet Boven - Spot - Dimmen Absoluut"),

            new KnxObject(KnxControlType.Feedback, KnxDataType.Duration, KnxGroupAddress.Parse("0/7/2"), "Aantal uren activiteit handdoekdroger"),
            new KnxObject(KnxControlType.Feedback, KnxDataType.Duration, KnxGroupAddress.Parse("0/7/4"), "Aantal uren activiteit oven"),
            new KnxObject(KnxControlType.Feedback, KnxDataType.Duration, KnxGroupAddress.Parse("0/7/6"), "Aantal uren activiteit microgolf"),
            new KnxObject(KnxControlType.Feedback, KnxDataType.Duration, KnxGroupAddress.Parse("0/7/8"), "Aantal uren activiteit stopcontacten buiten"),
            new KnxObject(KnxControlType.Feedback, KnxDataType.Duration, KnxGroupAddress.Parse("0/7/10"), "Aantal uren activiteit droogkast"),
            new KnxObject(KnxControlType.Feedback, KnxDataType.Duration, KnxGroupAddress.Parse("0/7/12"), "Aantal uren activiteit wasmachine"),
            new KnxObject(KnxControlType.Feedback, KnxDataType.Duration, KnxGroupAddress.Parse("0/7/14"), "Aantal uren activiteit diepvries"),
            new KnxObject(KnxControlType.Feedback, KnxDataType.Duration, KnxGroupAddress.Parse("0/7/16"), "Aantal uren activiteit koelkast"),
            new KnxObject(KnxControlType.Feedback, KnxDataType.Duration, KnxGroupAddress.Parse("0/7/18"), "Aantal uren activiteit vaatwas"),
            new KnxObject(KnxControlType.Feedback, KnxDataType.Duration, KnxGroupAddress.Parse("0/7/20"), "Aantal uren activiteit dampkap"),

            new KnxObject(KnxControlType.Feedback, KnxDataType.Duration, KnxGroupAddress.Parse("1/3/2"), "Boiler - Aantal uur brander"),
            new KnxObject(KnxControlType.Feedback, KnxDataType.Duration, KnxGroupAddress.Parse("1/3/8"), "Zonnecollector - Aantal uren gedraaid"),

            new KnxObject(KnxControlType.Feedback, KnxDataType.Current, KnxGroupAddress.Parse("0/7/3"), "Huidig verbruik handdoekdroger"),
            new KnxObject(KnxControlType.Feedback, KnxDataType.Current, KnxGroupAddress.Parse("0/7/5"), "Huidig verbruik oven"),
            new KnxObject(KnxControlType.Feedback, KnxDataType.Current, KnxGroupAddress.Parse("0/7/7"), "Huidig verbruik microgolf"),
            new KnxObject(KnxControlType.Feedback, KnxDataType.Current, KnxGroupAddress.Parse("0/7/9"), "Huidig verbruik stopcontacten buiten"),
            new KnxObject(KnxControlType.Feedback, KnxDataType.Current, KnxGroupAddress.Parse("0/7/11"), "Huidig verbruik droogkast"),
            new KnxObject(KnxControlType.Feedback, KnxDataType.Current, KnxGroupAddress.Parse("0/7/13"), "Huidig verbruik wasmachine"),
            new KnxObject(KnxControlType.Feedback, KnxDataType.Current, KnxGroupAddress.Parse("0/7/15"), "Huidig verbruik diepvries"),
            new KnxObject(KnxControlType.Feedback, KnxDataType.Current, KnxGroupAddress.Parse("0/7/17"), "Huidig verbruik koelkast"),
            new KnxObject(KnxControlType.Feedback, KnxDataType.Current, KnxGroupAddress.Parse("0/7/19"), "Huidig verbruik vaatwas"),
            new KnxObject(KnxControlType.Feedback, KnxDataType.Current, KnxGroupAddress.Parse("0/7/21"), "Huidig verbruik dampkap"),

            new KnxObject(KnxControlType.Feedback, KnxDataType.Temperature, KnxGroupAddress.Parse("0/4/0"), "Inkomhal (Plafond)"),
            new KnxObject(KnxControlType.Feedback, KnxDataType.Temperature, KnxGroupAddress.Parse("0/4/1"), "Toilet beneden (Plafond)"),
            new KnxObject(KnxControlType.Feedback, KnxDataType.Temperature, KnxGroupAddress.Parse("0/4/2"), "Berging (Plafond)"),
            new KnxObject(KnxControlType.Feedback, KnxDataType.Temperature, KnxGroupAddress.Parse("0/4/3"), "Garage (Plafond)"),
            new KnxObject(KnxControlType.Feedback, KnxDataType.Temperature, KnxGroupAddress.Parse("0/4/4"), "Nachthal trap (Plafond)"),
            new KnxObject(KnxControlType.Feedback, KnxDataType.Temperature, KnxGroupAddress.Parse("0/4/5"), "Nachthal badkamer (Plafond)"),
            new KnxObject(KnxControlType.Feedback, KnxDataType.Temperature, KnxGroupAddress.Parse("0/4/6"), "Badkamer (Plafond)"),
            new KnxObject(KnxControlType.Feedback, KnxDataType.Temperature, KnxGroupAddress.Parse("0/4/7"), "Toilet boven (Plafond)"),
            new KnxObject(KnxControlType.Feedback, KnxDataType.Temperature, KnxGroupAddress.Parse("0/4/8"), "Slaapkamer 1 (David)"),
            new KnxObject(KnxControlType.Feedback, KnxDataType.Temperature, KnxGroupAddress.Parse("0/4/9"), "Slaapkamer 2 (Opslag)"),
            new KnxObject(KnxControlType.Feedback, KnxDataType.Temperature, KnxGroupAddress.Parse("0/4/10"), "Slaapkamer 3 (Abby)"),
            new KnxObject(KnxControlType.Feedback, KnxDataType.Temperature, KnxGroupAddress.Parse("0/4/11"), "Bureau"),
            new KnxObject(KnxControlType.Feedback, KnxDataType.Temperature, KnxGroupAddress.Parse("0/4/12"), "Badkamer"),
            new KnxObject(KnxControlType.Feedback, KnxDataType.Temperature, KnxGroupAddress.Parse("0/4/13"), "Weerstation"),
            new KnxObject(KnxControlType.Feedback, KnxDataType.Temperature, KnxGroupAddress.Parse("0/4/14"), "Keuken"),

            new KnxObject(KnxControlType.Feedback, KnxDataType.Temperature, KnxGroupAddress.Parse("1/3/0"), "Boiler - Buitentemperatuur"),
            new KnxObject(KnxControlType.Feedback, KnxDataType.Temperature, KnxGroupAddress.Parse("1/3/1"), "Boiler - Temperatuur"),
            new KnxObject(KnxControlType.Feedback, KnxDataType.Temperature, KnxGroupAddress.Parse("1/3/5"), "Zonnecollector - Zonnecollector temperatuur"),
            new KnxObject(KnxControlType.Feedback, KnxDataType.Temperature, KnxGroupAddress.Parse("1/3/6"), "Zonnecollector - Zonnecylinder temperatuur"),
            new KnxObject(KnxControlType.Feedback, KnxDataType.Temperature, KnxGroupAddress.Parse("1/3/12"), "Vloerverwarming - Temperatuur"),
            new KnxObject(KnxControlType.Feedback, KnxDataType.Temperature, KnxGroupAddress.Parse("1/3/17"), "Warmwater - Temperatuur"),
            new KnxObject(KnxControlType.Feedback, KnxDataType.Temperature, KnxGroupAddress.Parse("1/3/18"), "Warmwater - Temperatuur Discharge"),

            new KnxObject(KnxControlType.Feedback, KnxDataType.LightStrength, KnxGroupAddress.Parse("0/3/0"), "Lichtsterkte in inkomhal"),
            new KnxObject(KnxControlType.Feedback, KnxDataType.LightStrength, KnxGroupAddress.Parse("0/3/1"), "Lichtsterkte in toilet beneden"),
            new KnxObject(KnxControlType.Feedback, KnxDataType.LightStrength, KnxGroupAddress.Parse("0/3/2"), "Lichtsterkte in berging"),
            new KnxObject(KnxControlType.Feedback, KnxDataType.LightStrength, KnxGroupAddress.Parse("0/3/3"), "Lichtsterkte in garage"),
            new KnxObject(KnxControlType.Feedback, KnxDataType.LightStrength, KnxGroupAddress.Parse("0/3/4"), "Lichtsterkte in nachthal trap"),
            new KnxObject(KnxControlType.Feedback, KnxDataType.LightStrength, KnxGroupAddress.Parse("0/3/5"), "Lichtsterkte in nachthal badkamer"),
            new KnxObject(KnxControlType.Feedback, KnxDataType.LightStrength, KnxGroupAddress.Parse("0/3/6"), "Lichtsterkte in badkamer"),
            new KnxObject(KnxControlType.Feedback, KnxDataType.LightStrength, KnxGroupAddress.Parse("0/3/7"), "Lichtsterkte in toilet boven"),
            new KnxObject(KnxControlType.Feedback, KnxDataType.LightStrength, KnxGroupAddress.Parse("0/3/8"), "Lichtsterkte buiten 1"),
            new KnxObject(KnxControlType.Feedback, KnxDataType.LightStrength, KnxGroupAddress.Parse("0/3/9"), "Lichtsterkte buiten schemering"),
            new KnxObject(KnxControlType.Feedback, KnxDataType.LightStrength, KnxGroupAddress.Parse("0/3/10"), "Lichtsterkte buiten 2"),
            new KnxObject(KnxControlType.Feedback, KnxDataType.LightStrength, KnxGroupAddress.Parse("0/3/11"), "Lichtsterkte buiten 3"),

            new KnxObject(KnxControlType.Feedback, KnxDataType.Speed, KnxGroupAddress.Parse("1/0/0"), "Windsnelheid buiten"),

            new KnxObject(KnxControlType.Feedback, KnxDataType.Time, KnxGroupAddress.Parse("0/0/1"), "Centrale Tijd"),

            new KnxObject(KnxControlType.Feedback, KnxDataType.Date, KnxGroupAddress.Parse("0/0/2"), "Centrale Datum"),

            new KnxObject(KnxControlType.Feedback, KnxDataType.EnergyWattHour, KnxGroupAddress.Parse("1/3/10"), "Zonnecollector - Warmteopbrengst vandaag"),

            new KnxObject(KnxControlType.Feedback, KnxDataType.EnergyKiloWattHour, KnxGroupAddress.Parse("1/3/9"), "Zonnecollector - Warmteopbrengst"),
        };
    }
}
