# Functional Living Api Test
# Get all lights

GET http://127.0.0.1:9000/v1/lights HTTP/1.1
content-type: application/json

###

# Functional Living Api Test
# Turn on a light

GET http://127.0.0.1:9000/v1/lights/5f3bde85-7d47-5cfb-9a6f-e89d4c18b82d/on HTTP/1.1
content-type: application/json

###

# Functional Living Api Test
# Turn off a light

GET http://127.0.0.1:9000/v1/lights/5f3bde85-7d47-5cfb-9a6f-e89d4c18b82d/off HTTP/1.1
content-type: application/json
