# Functional Living Api Test
# Get all lights

GET http://127.0.0.1:9000/v1/lights HTTP/1.1
content-type: application/json

###

# Functional Living Api Test
# Turn on a light

GET http://127.0.0.1:9000/v1/lights/82395c55-aea8-5218-a707-7b438c69b5bd/on HTTP/1.1
content-type: application/json

###

# Functional Living Api Test
# Turn on a light

GET http://127.0.0.1:9000/v1/lights/82395c55-aea8-5218-a707-7b438c69b5bd/off HTTP/1.1
content-type: application/json
