# Functional Living Knx Sender Test
# Turn off the Living light

POST http://127.0.0.1:9001/v1/knx HTTP/1.1
content-type: application/json

{
  destinationAddress: "2/2/10",
  dataType: "bool",
  state: "false"
}

###

# Functional Living Knx Sender Test
# Turn on the Living light

POST http://127.0.0.1:9001/v1/knx HTTP/1.1
content-type: application/json

{
  destinationAddress: "2/2/10",
  dataType: "bool",
  state: "true"
}
